from __future__ import annotations

from pathlib import Path

from .parser import read_structure_files


def export_structure(path: str = ".", output: str = "STRUCTURE_CONTEXT.md") -> dict:
    """
    Merge structure files into one agent-facing context file.
    """
    root = Path(path)
    chunks = [
        "# Structure Context",
        "",
        "Generated by Structure Rule Kit.",
        "",
    ]
    for label, content in read_structure_files(path):
        chunks.append(f"## {label}")
        chunks.append("")
        chunks.append(content.strip())
        chunks.append("")

    output_path = root / output
    output_path.write_text("\n".join(chunks).rstrip() + "\n", encoding="utf-8")
    return {"output": str(output_path), "files": [label for label, _ in read_structure_files(path)]}
